String regionForecastTestData =
    "<RegionForecast><RegionNameThai>ภาคเหนือ</RegionNameThai><RegionNameEnglish>Northern Part</RegionNameEnglish><DescriptionThai>มีฝนฟ้าคะนองร้อยละ 40 ของพื้นที่ ส่วนมากบริเวณจังหวัดแม่ฮ่องสอน เชียงใหม่ ตาก สุโขทัย กำแพงเพชร พิจิตร พิษณุโลก และเพชรบูรณ์ อุณหภูมิต่ำสุด 23-26 องศาเซลเซียส อุณหภูมิสูงสุด 33-38 องศาเซลเซียส ลมตะวันตกเฉียงใต้ ความเร็ว 5-15 กม./ชม. </DescriptionThai><DescriptionEnglish>Scattered thundershowers mostly in Mae Hong Son, Chiang Mai, Tak, Sukhothai, Kamphaeng Phet, Pichit, Pitsanulok, Pichit and Phetchabun. Minimum temperature 23-26 &deg;C. Maximum temperature 33-38 &deg;C. Southwesterly winds 5-15 km/hr. </DescriptionEnglish></RegionForecast>";

String dailyForecastTestData = '<DailyForecast>'
    '<Date>21/6/2022</Date>'
    '<OverallDescriptionThai>พยากรณ์อากาศ 24 ชั่วโมงข้างหน้า มรสุมตะวันตกเฉียงใต้ที่พัดปกคลุมทะเลอันดามัน ประเทศไทย และอ่าวไทยมีกำลังอ่อน แต่ยังคงมีฝนฟ้าคะนองเกิดขึ้นได้บางพื้นที่ และมีลมกระโชกแรงบางแห่ง บริเวณภาคตะวันออกเฉียงเหนือ และภาคกลาง ขอให้ประชาชนระมัดระวังอันตรายจากฝนฟ้าคะนองและลมกระโชกแรงไว้ด้วย ส่วนคลื่นลมบริเวณทะเลอันดามันและอ่าวไทยมีกำลังอ่อน โดยมีคลื่นสูงประมาณ 1 เมตร บริเวณที่มีฝนฟ้าคะนองคลื่นสูงมากกว่า 1 เมตร ขอให้ชาวเรือในบริเวณดังกล่าวเดินเรือด้วยความระมัดระวังบริเวณที่มีฝนฟ้าคะนองไว้ด้วย </OverallDescriptionThai>'
    '<OverallDescriptionEnglish>The weak southwest monsoon prevails across the Andaman Sea, Thailand and the Gulf of Thailand. Thundershower is likely in the whole country gusty wind in the Northeast and the Central.. People in these area should beware of severe conditions. The weak wind and wave prevail across the Andaman Sea and the Gulf of Thailand are about 1 meter high and above 1 meters high in thundershowers. All ships should proceed with caution and keep off thundershowers.</OverallDescriptionEnglish>'
    '<RegionsForecast>'
    '<RegionForecast>'
    '<RegionNameThai>ภาคเหนือ</RegionNameThai>'
    '<RegionNameEnglish>Northern Part</RegionNameEnglish>'
    '<DescriptionThai>มีฝนฟ้าคะนองร้อยละ 40 ของพื้นที่ ส่วนมากบริเวณจังหวัดแม่ฮ่องสอน เชียงใหม่ ตาก สุโขทัย กำแพงเพชร พิจิตร พิษณุโลก และเพชรบูรณ์ อุณหภูมิต่ำสุด 23-26 องศาเซลเซียส อุณหภูมิสูงสุด 33-38 องศาเซลเซียส ลมตะวันตกเฉียงใต้ ความเร็ว 5-15 กม./ชม. </DescriptionThai>'
    '<DescriptionEnglish>Scattered thundershowers mostly in Mae Hong Son, Chiang Mai, Tak, Sukhothai, Kamphaeng Phet, Pichit, Pitsanulok, Pichit and Phetchabun. Minimum temperature 23-26 &deg;C. Maximum temperature 33-38 &deg;C. Southwesterly winds 5-15 km/hr. </DescriptionEnglish>'
    '</RegionForecast>'
    '<RegionForecast>'
    '<RegionNameThai>ภาคตะวันออกเฉียงเหนือ</RegionNameThai>'
    '<RegionNameEnglish>Northeastern Part</RegionNameEnglish>'
    '<DescriptionThai>มีฝนฟ้าคะนองร้อยละ 30 ของพื้นที่ กับมีลมกระโชกแรงบางแห่ง บริเวณจังหวัดเลย หนองคาย บึงกาฬ นครพนม ชัยภูมิ นครราชสีมา บุรีรัมย์ สุรินทร์ ศรีสะเกษ และอุบลราชธานี อุณหภูมิต่ำสุด 23-26 องศาเซลเซียส อุณหภูมิสูงสุด 35-37 องศาเซลเซียส ลมตะวันตกเฉียงใต้ ความเร็ว 10-15 กม./ชม. </DescriptionThai>'
    '<DescriptionEnglish>Isolated thundershowers and gusty wind in Leoi, Nong Khai, Bueng Kan, Nakhon Phanom, Chaiyaphum, Nakhon Ratchasima, Buri Ram, Surin, Si Sa Ket and Ubon Ratchathani. Minimum temperature 23-26 &deg;C. Maximum temperature 35-37 &deg;C. Southwesterly winds 10-15 km/hr. </DescriptionEnglish>'
    '</RegionForecast>'
    '<RegionForecast>'
    '<RegionNameThai>ภาคกลาง</RegionNameThai>'
    '<RegionNameEnglish>Central Part</RegionNameEnglish>'
    '<DescriptionThai>มีฝนฟ้าคะนองร้อยละ 40 ของพื้นที่ กับมีลมกระโชกแรงบางแห่ง บริเวณจังหวัดนครสวรรค์ อุทัยธานี กาญจนบุรี สุพรรณบุรี ลพบุรี และสระบุรี อุณหภูมิต่ำสุด 24-26 องศาเซลเซียส อุณหภูมิสูงสุด 36-38 องศาเซลเซียส ลมตะวันตกเฉียงใต้ ความเร็ว 10-15 กม./ชม. </DescriptionThai>'
    '<DescriptionEnglish>Scattered thundershowers and gusty wind in Nakhon Sawan, Uthai Thani, Kanchanaburi, Suphan Buri, Lop Buri and Saraburi. Minimum temperature 24-26 &deg;C. Maximum temperature 36-38 &deg;C. Southwesterly winds 10-15 km/hr. </DescriptionEnglish>'
    '</RegionForecast>'
    '<RegionForecast>'
    '<RegionNameThai>ภาคตะวันออก</RegionNameThai>'
    '<RegionNameEnglish>Eastern Part</RegionNameEnglish>'
    '<DescriptionThai>มีฝนฟ้าคะนองร้อยละ 30 ของพื้นที่ ส่วนมากบริเวณจังหวัดชลบุรี ระยอง จันทบุรี และตราด อุณหภูมิต่ำสุด 24-27 องศาเซลเซียส อุณหภูมิสูงสุด 34-37 องศาเซลเซียส ลมตะวันตกเฉียงใต้ ความเร็ว 15-30 กม./ชม. ทะเลมีคลื่นสูงประมาณ 1 เมตร บริเวณที่มีฝนฟ้าคะนองคลื่นสูงมากกว่า 1 เมตร </DescriptionThai>'
    '<DescriptionEnglish>Isolated thundershowers mostly in Chon Buri, Rayong, Chanthaburi and Trat. Minimum temperature 24-27 &deg;C. Maximum temperature 34-37 &deg;C. Southwesterly winds 15-30 km/hr. Wave height about 1 meter and above 1 meter in thundershowers. </DescriptionEnglish>'
    '</RegionForecast>'
    '<RegionForecast>'
    '<RegionNameThai>ภาคใต้ (ฝั่งตะวันออก)</RegionNameThai>'
    '<RegionNameEnglish>Southern Part (East Coast)</RegionNameEnglish>'
    '<DescriptionThai>มีฝนฟ้าคะนองร้อยละ 40 ของพื้นที่ ส่วนมากบริเวณจังหวัดเพชรบุรี สุราษฎร์ธานี นครศรีธรรมราช พัทลุง สงขลา ปัตตานี ยะลา และนราธิวาส อุณหภูมิต่ำสุด 24-26 องศาเซลเซียส อุณหภูมิสูงสุด 33-36 องศาเซลเซียส ลมตะวันตกเฉียงใต้ ความเร็ว 15-30 กม./ชม. ทะเลมีคลื่นสูงประมาณ 1 เมตร บริเวณที่มีฝนฟ้าคะนองคลื่นสูงมากกว่า 1 เมตร </DescriptionThai>'
    '<DescriptionEnglish>Scattered thundershowers mostly in Petchaburi, Surat Thani, Nakhon Si Thammarat, Songkhla, Pattani, Yala and Narathiwat. Minimum temperature 24-26 &deg;C. Maximum temperature 33-36 &deg;C. Southwesterly winds 15-30 km/hr. Wave height about 1 meter and above 1 meter in thundershowers. </DescriptionEnglish>'
    '</RegionForecast>'
    '<RegionForecast>'
    '<RegionNameThai>ภาคใต้ (ฝั่งตะวันตก)</RegionNameThai>'
    '<RegionNameEnglish>Southern Part (West Coast)</RegionNameEnglish>'
    '<DescriptionThai>มีฝนฟ้าคะนองร้อยละ 40 ของพื้นที่ ส่วนมากบริเวณจังหวัดพังงา ภูเก็ต ตรัง และสตูล อุณหภูมิต่ำสุด 23-25 องศาเซลเซียส อุณหภูมิสูงสุด 32-34 องศาเซลเซียส ลมตะวันตกเฉียงใต้ ความเร็ว 15-30 กม./ชม. ทะเลมีคลื่นสูงประมาณ 1 เมตร บริเวณที่มีฝนฟ้าคะนองคลื่นสูงมากกว่า 1 เมตร </DescriptionThai>'
    '<DescriptionEnglish>Scattered thundershowers mostly in Phangnga, Phuket, Trang and Satun. Minimum temperature 23-25 &deg;C. Maximum temperature 32-34 &deg;C. Southwesterly winds 15-30 km/hr. Wave height about 1 meter and above 1 meter in thundershowers. </DescriptionEnglish>'
    '</RegionForecast>'
    '<RegionForecast>'
    '<RegionNameThai>กรุงเทพมหานครและปริมณฑล</RegionNameThai>'
    '<RegionNameEnglish>Metropolitan</RegionNameEnglish>'
    '<DescriptionThai>มีฝนฟ้าคะนองร้อยละ 40 ของพื้นที่ ส่วนมากในระหว่างบ่ายถึงค่ำ อุณหภูมิต่ำสุด 24-25 องศาเซลเซียส อุณหภูมิสูงสุด 34-37 องศาเซลเซียส ลมตะวันตกเฉียงใต้ ความเร็ว 10-15 กม./ชม. </DescriptionThai>'
    '<DescriptionEnglish>Isolated thundershowers mostly in the afternoon to evening. Minimum temperature 24-25 &deg;C. Maximum temperature 34-37 &deg;C. Southwesterly winds 10-15 km/hr. </DescriptionEnglish>'
    '</RegionForecast>'
    '</RegionsForecast>'
    '</DailyForecast>';
